on: push
jobs:
  run:
    runs-on: ubuntu-latest
    name: treebeard: Continuous Integration for Python Data Science supporting Jupyter Notebooks
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: treebeardtech/treebeard@master
